Unlike lists, numpy arrays are used to perform arithmatic operations..it is faster and consumes less memory than list..all data type must be same

In [ ]:
import numpy as np
a=np.array([22,34,14,56])
b=np.array([21,33,45,64])
print(a)
print(b)
print(a+b)

In [ ]:
# a=np.array([23,45,'wjhs'])
# a=np.array([23,45, 22.34,'wjhs'])
a=np.array([23,45, 22.34])
print(a)

Important difference b/w lists and arrays
->In lists there can be any number of lists with any number of variables
->But In arrays must be same number of elements in all lists

In [ ]:
import numpy as np
# a=np.array([22,11],[44,55,26])   //error
a=np.array([[22,33,55,11],[44,55,11,22],[24,85,11,62]])
# print(type(a))
print(np.shape(a))   #defines rows,columns of matrix
print(np.size(a))   #toal number of elements
print(np.ndim(a))   #number of array dimensions
print(a.dtype)      #data type
print(a.shape)
print(a.astype(str))   #converts as typecasting
print(a.astype(int))

# slicing
# a=np.array([22,33,55,11])
# print(a[1:3])
# print(a[:3])

# a=np.array([[22,33,55,11],[44,55,11,22]])
# print(a[0,1:3])   #0-> 1st row
# print(a[1,1:3])   #1-> 2nd row

Mathematical operations , join and split

In [ ]:
import numpy as np
a1=np.array([30,40,50,60])
a2=np.array([22,36,15,70])
# print(a1+a2)
print(np.add(a1,a2))
# print(a1-a2)
print(np.subtract(a1,a2))
# print(a1*a2)
print(np.multiply(a1,a2))
# print(a1/a2)
print(np.divide(a1,a2))

In [ ]:
a1=np.array([3,4,5,2])
a2=np.array([3])
# print(pow(a1,a2))
print(np.power(a1,a2))
a3=np.array([9,4,25,36])
print(np.sqrt(a3))
a4=np.array([22,36,15,70])
print(np.concatenate([a1,a4]))

In [ ]:
a1=np.array([[22,3],[15,40]])
a2=np.array([[2,36],[5,70]])
# concatenate by axis
# print(np.concatenate([a1,a2],axis=0))   #horizontal concatenation
# print(np.concatenate([a1,a2],axis=1))   #vertical concatenation
print(np.vstack([a1,a2]))   #horizontal concatenation
print(np.hstack([a1,a2]))   #vertical concatenation

In [ ]:
a=np.array([11,22,33,44,55,66,77,88])
b=np.array_split(a,3)   #devides into 3 arrays
print(b)

Adding and removing

In [ ]:
import numpy as np
# Append
a=np.array([22,44,56])
# print(np.append(a,77))    
a1=np.array([[22,44,56],[11,33,55]])
print(np.append(a1,[12,16])) #for 2-d arrays it first converts it into 1-d array then appends

print()

# Insert
print(np.insert(a,2,12))    #array,index,valuye
print(np.insert(a1,1,[32,33,34],axis=0))    #for 2d arrays

print()

#delete
print(np.delete(a,2))
print(a1)
print()
print(np.delete(a1,2,axis=1))   #deletes column wise
print(np.delete(a1,1,axis=0))   #deletes row wise


Sort,Search,Filter

In [ ]:
# sort
# ar=np.array([3,7,1,9,2,4])    #1-d arry
# ar=np.array([[3,7,1,9,2,4],[11,33,77,22,12,8]]) #2-d array
# print(np.sort(ar))


#search
ar=np.array([3,6,12,8,45,4,5])
# s=np.where(ar==4)   #return index where the value present
s=np.where( ar % 2 == 0 )
print(s)

# we can also use searchsorted func but we have to initialize the array in sorted order
ar1=np.array([3,6,8,11,22])
ss=np.searchsorted(ar1,22)
print(ss)


#filter
ar2=np.array([3,6,12,8,45])
# f=[False,False,False,True,False]
# new=ar2[f]
# print(new)  #the values defined as True only be printed

# f=ar2>7
f= ar2 % 2 == 0
new=ar2[f]
print(new)

Aggregating Functions

In [11]:
import numpy as np
x=np.array([22,33,11,44,32])
print(np.max(x))
print(np.min(x))
print(np.sum(x))
print(np.size(x))
print(np.mean(x))
print(np.cumsum(x))
print(np.cumprod(x))

44
11
142
5
28.4
[ 22  55  66 110 142]
[      22      726     7986   351384 11244288]


In [16]:
# to find the total price of shopping
a=[22,11,43,5,66,8]
b=[10,20,30,40,60,50]
price=np.array(a)
quantity=np.array(b)
print(price,"\n",quantity)
s=(np.cumprod([price,quantity],axis=0))
# print(s)
print(s[1])
print(s[1].sum())

[22 11 43  5 66  8] 
 [10 20 30 40 60 50]
[[  22   11   43    5   66    8]
 [ 220  220 1290  200 3960  400]]
6290


*** Statistical Functions ****

In [17]:
import numpy as np
import statistics as stats
baked_food=[200,212,354,466,321,226,200,324]
a=np.array(baked_food)
print(np.mean(baked_food))
print(np.median(baked_food))
print(stats.mode(baked_food))
# standerd deviation is used to determine the quality of our product
# the higher std value difines we need to optimize it by reducing the value
print(np.std(baked_food))   #standerd deviation
print(np.var(baked_food))   #variation is the power of stand.deviation


287.875
273.5
200
89.11570779049
7941.609375


In [18]:
# - 1 represents inversly proportional relationship
# + 1 represents proportional relationship
# 0 represents no relationship
tobacco_consumption = [30,50,10,30,50,40]
deaths = [100,120,70,120,110,111]

# corrcoef--> coeficient of corelation , it tells us about the data
print(np.corrcoef([tobacco_consumption,deaths]))
# here between (0-1) result indicates tobacco_consumption increment also deaths increasing

[[1.         0.81165962]
 [0.81165962 1.        ]]


In [19]:
price = [300,200,100,150,200]
sales = [10,20,30,17,4]

print(np.corrcoef([price,sales]))
# here between negetive result indicates sales increment when deaths decreases

[[ 1.         -0.69395784]
 [-0.69395784  1.        ]]
